# Generated by Django 6.0.3 on 2026-03-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_todo_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="name",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
